function [ pre_I_seg ] = cal_I_oblique_dwn( p_18MidCrdnt, p_18Phi )
    
    pre_I_seg = 0;
    E_field = zeros(4, 3);
    TriVec  = zeros(4, 3);

    E_field(1, :) = calE( squeeze( p_18MidCrdnt(1, 1, :) ), squeeze( p_18MidCrdnt(2, 1, :) ), ...
                            squeeze( p_18MidCrdnt(2, 4, :) ), squeeze( p_18MidCrdnt(2, 5, :) ), ...
                            p_18Phi(1, 1, :), p_18Phi(2, 1, :), p_18Phi(2, 4, :), p_18Phi(2, 5, :) );
    E_field(2, :) = calE( squeeze( p_18MidCrdnt(1, 1, :) ), squeeze( p_18MidCrdnt(1, 2, :) ), ...
                            squeeze( p_18MidCrdnt(2, 2, :) ), squeeze( p_18MidCrdnt(2, 5, :) ), ...
                            p_18Phi(1, 1, :), p_18Phi(1, 2, :), p_18Phi(2, 2, :), p_18Phi(2, 5, :) );
    E_field(3, :) = calE( squeeze( p_18MidCrdnt(1, 2, :) ), squeeze( p_18MidCrdnt(1, 3, :) ), ...
                            squeeze( p_18MidCrdnt(2, 2, :) ), squeeze( p_18MidCrdnt(2, 5, :) ), ...
                            p_18Phi(1, 2, :), p_18Phi(1, 3, :), p_18Phi(2, 2, :), p_18Phi(2, 5, :) );
    E_field(4, :) = calE( squeeze( p_18MidCrdnt(1, 3, :) ), squeeze( p_18MidCrdnt(2, 3, :) ), ...
                            squeeze( p_18MidCrdnt(2, 5, :) ), squeeze( p_18MidCrdnt(2, 6, :) ), ...
                            p_18Phi(1, 3, :), p_18Phi(2, 3, :), p_18Phi(2, 5, :), p_18Phi(2, 6, :) );

    TriVec(1, :) = calTriVec( squeeze( p_18MidCrdnt(1, 1, :) ), squeeze( p_18MidCrdnt(2, 4, :) ), ...
                                squeeze( p_18MidCrdnt(2, 5, :) ) );
    TriVec(2, :) = calTriVec( squeeze( p_18MidCrdnt(1, 1, :) ), squeeze( p_18MidCrdnt(2, 5, :) ), ...
                                squeeze( p_18MidCrdnt(1, 2, :) ) );
    TriVec(3, :) = calTriVec( squeeze( p_18MidCrdnt(1, 2, :) ), squeeze( p_18MidCrdnt(2, 5, :) ), ...
                                squeeze( p_18MidCrdnt(1, 3, :) ) );
    TriVec(4, :) = calTriVec( squeeze( p_18MidCrdnt(1, 3, :) ), squeeze( p_18MidCrdnt(2, 5, :) ), ...
                                squeeze( p_18MidCrdnt(2, 6, :) ) );

    pre_I_seg = sum(sum( ( E_field .* TriVec ) ));

end