clc; clear; 
% fname = 'E:\Kevin\CapaReal\Case0103';
fname = 'D:\Kevin\GraduateSchool\Projects\ProjectBio\Simlation\CapaReal\Case0103';
CaseName = 'Power250';
% V_0 = 78.75;
% Shift2d;
% save( strcat(fname, '\', CaseName, '.mat') );
load( strcat(fname, '\', CaseName, '.mat') );
fname = 'D:\Kevin\GraduateSchool\Projects\ProjectBio\Simlation\CapaReal\Case0103';
CurrentEst;

clc; clear;
% fname = 'E:\Kevin\CapaReal\Case0103';
fname = 'D:\Kevin\GraduateSchool\Projects\ProjectBio\Simlation\CapaReal\Case0103';
CaseName = 'Power280';
% V_0 = 83.34;
% Shift2d;
% save( strcat(fname, '\', CaseName, '.mat') );
load( strcat(fname, '\', CaseName, '.mat') );
fname = 'D:\Kevin\GraduateSchool\Projects\ProjectBio\Simlation\CapaReal\Case0103';
CurrentEst;

clc; clear;
% fname = 'E:\Kevin\CapaReal\Case0103';
fname = 'D:\Kevin\GraduateSchool\Projects\ProjectBio\Simlation\CapaReal\Case0103';
CaseName = 'Power300';
% V_0 = 86.26;
% Shift2d;
% save( strcat(fname, '\', CaseName, '.mat') );
load( strcat(fname, '\', CaseName, '.mat') );
fname = 'D:\Kevin\GraduateSchool\Projects\ProjectBio\Simlation\CapaReal\Case0103';
CurrentEst;